apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: i239e1xik-java-springboot-gitops-repository
spec:
  url: https://github.com/tnevrlka-rhtap/i239e1xik-java-springboot-gitops